"""add_users_table

Revision ID: 7fceefecdbfb
Revises: add9c881d6b3
Create Date: 2026-05-05 20:32:06.028690

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '7fceefecdbfb'
down_revision: str | Sequence[str] | None = 'add9c881d6b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
