"""initial_schema

Revision ID: add9c881d6b3
Revises: 
Create Date: 2026-05-05 19:00:59.943038

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add9c881d6b3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_code', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=False),
    sa.Column('normal_balance', sa.String(), nullable=False),
    sa.Column('paystub_mapping', sa.String(), nullable=True),
    sa.Column('is_memo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_type IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense', 'Memo Asset*')", name='ck_account_type'),
    sa.CheckConstraint("normal_balance IN ('debit', 'credit')", name='ck_normal_balance'),
    sa.PrimaryKeyConstraint('account_code')
    )
    op.create_table('periods',
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'pending_review', 'pending_close', 'closed')", name='ck_period_status'),
    sa.PrimaryKeyConstraint('period_id'),
    sa.UniqueConstraint('period_start')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('source_account_code', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("document_type IN ('paystub', 'bank_statement', 'credit_card', 'investment', 'mortgage_statement', 'manual', 'opening_balances')", name='ck_document_type'),
    sa.CheckConstraint("parse_status IN ('pending', 'in_progress', 'complete', 'failed')", name='ck_parse_status'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.ForeignKeyConstraint(['source_account_code'], ['accounts.account_code'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('reconciliation',
    sa.Column('recon_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.Integer(), nullable=False),
    sa.Column('computed_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stated_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gap', sa.Numeric(precision=15, scale=2), sa.Computed('stated_balance - computed_balance', ), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('reconciled', 'adjusted', 'pending')", name='ck_recon_status'),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.account_code'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.PrimaryKeyConstraint('recon_id')
    )
    op.create_table('stated_balances',
    sa.Column('balance_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.Integer(), nullable=False),
    sa.Column('stated_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.account_code'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.PrimaryKeyConstraint('balance_id'),
    sa.UniqueConstraint('period_id', 'account_code', name='uq_stated_balance_period_account')
    )
    op.create_table('journal_entries',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('is_adjusting', sa.Boolean(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("created_by IN ('python', 'user')", name='ck_entry_created_by'),
    sa.CheckConstraint("source_type IN ('paystub', 'statement', 'manual', 'adjusting', 'closing')", name='ck_entry_source_type'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('ix_journal_entry_date', 'journal_entries', ['entry_date'], unique=False)
    op.create_table('journal_lines',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.Integer(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name='debit_or_credit'),
    sa.CheckConstraint('credit_amount >= 0', name='ck_credit_non_negative'),
    sa.CheckConstraint('debit_amount >= 0', name='ck_debit_non_negative'),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.account_code'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_journal_line_account_code', 'journal_lines', ['account_code'], unique=False)
    op.create_index('ix_journal_line_entry_id', 'journal_lines', ['entry_id'], unique=False)
    op.create_table('raw_transactions',
    sa.Column('raw_txn_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('suggested_account_code', sa.Integer(), nullable=True),
    sa.Column('classifier_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('staged', 'approved', 'rejected', 'posted')", name='ck_raw_txn_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.entry_id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.ForeignKeyConstraint(['suggested_account_code'], ['accounts.account_code'], ),
    sa.PrimaryKeyConstraint('raw_txn_id')
    )
    op.create_index('ix_raw_txn_dedup_hash', 'raw_transactions', ['dedup_hash'], unique=False)
    op.create_index('ix_raw_txn_flagged', 'raw_transactions', ['is_flagged'], unique=False, postgresql_where='is_flagged = TRUE')
    op.create_index('ix_raw_txn_period_id', 'raw_transactions', ['period_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('raw_txn_id', sa.Uuid(), nullable=False),
    sa.Column('review_type', sa.String(), nullable=False),
    sa.Column('llm_suggestion', sa.JSON(), nullable=True),
    sa.Column('llm_reasoning', sa.String(), nullable=True),
    sa.Column('user_decision', sa.String(), nullable=True),
    sa.Column('resolved_account_code', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("review_type IN ('unclassified', 'ambiguous', 'adjusting')", name='ck_review_type'),
    sa.CheckConstraint("user_decision IS NULL OR user_decision IN ('approved', 'overridden', 'skipped')", name='ck_user_decision'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], ),
    sa.ForeignKeyConstraint(['raw_txn_id'], ['raw_transactions.raw_txn_id'], ),
    sa.ForeignKeyConstraint(['resolved_account_code'], ['accounts.account_code'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('ix_review_queue_pending', 'review_queue', ['user_decision'], unique=False, postgresql_where=sa.text('user_decision IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_queue_pending', table_name='review_queue', postgresql_where=sa.text('user_decision IS NULL'))
    op.drop_table('review_queue')
    op.drop_index('ix_raw_txn_period_id', table_name='raw_transactions')
    op.drop_index('ix_raw_txn_flagged', table_name='raw_transactions', postgresql_where='is_flagged = TRUE')
    op.drop_index('ix_raw_txn_dedup_hash', table_name='raw_transactions')
    op.drop_table('raw_transactions')
    op.drop_index('ix_journal_line_entry_id', table_name='journal_lines')
    op.drop_index('ix_journal_line_account_code', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index('ix_journal_entry_date', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('stated_balances')
    op.drop_table('reconciliation')
    op.drop_table('documents')
    op.drop_table('periods')
    op.drop_table('accounts')
    # ### end Alembic commands ###
